# This script is called by the .github/workflows/release.yml workflow to create Gerbers for selected Fab houses.
# This KiBot script generates gerbers, drill, bom, and position files for submitting
# two layer boards to JLCPCB.
kibot:
  version: 1
  
globals:
  # Make it match the name used by your project
  field_lcsc_part: LCSC
  
  # Filters for KiBot warnings
  filters:
    - filter: Ignore Panel multiple components
      number: 164
#   # This will undo the `set_text_variables` when we run it locally
#   restore_project: true
#   # We will use a value externally formatted
#   time_reformat: false

filters:
  - name: only_jlc_parts
    comment: "Only parts with JLC code"
    type: generic
    include_only:
      - column: "LCSC"
        regex: '^C\d+'
  - name: fix_rotation
    comment: 'Adjust rotation for JLC'
    type: rot_footprint
    negative_bottom: false
    # mirror_bottom: true
    # Rotation list from https://github.com/matthewlai/JLCKicadTools/blob/master/jlc_kicad_tools/cpl_rotations_db.csv
    rotations:
      - ["^R_Array_Convex_",90]
      - ["^R_Array_Concave_",90]
      - ["^SOT-223",180]
      - ["^SOT-23",-90]
      - ["^SOT-89",180]
      - ["^TSOT-23",180]
      - ["^SOT-353",180]
      - ["^SOT-363",180]
      - ["^LQFP-",270]
      - ["^TQFP-",270]
      - ["^SOP-4_",0]
      - ["^SOP-(?!18_)",270]
      - ["^TSSOP-",270]
      - ["^SSOP-",270]
      - ["^DFN-",270]
      - ["^SOIC-",270]
      - ["^SOP-18_",0]
      - ["^VSSOP-8_3.0x3.0mm_P0.65mm",270]
      - ["^VSSOP-8_",180]
      - ["^VSSOP-10_",270]
      - ["^VSON-8_",270]
      - ["^TSOP-6",270]
      - ["^UDFN-10",270]
      - ["^USON-10",270]
      - ["^TDSON-8-1",270]
      - ["^CP_EIA-",180]
      - ["^CP_Elec_8x5.4",180]
      - ["^CP_Elec_8x10.5",180]
      - ["^CP_Elec_6.3x7.7",180]
      - ["^CP_Elec_8x6.7",180]
      - ["^CP_Elec_8x10",180]
      - ["^CP_Elec_10x10",180]
      - ["^(.*?_|V)?QFN-(16|20|24|28|40)(-|_|$)",270]
      - ["^Bosch_LGA-8_2x2.5mm_P0.65mm_ClockwisePinNumbering",90]
      - ["^PowerPAK_SO-8_Single",270]
      - ["^HTSSOP-28-1EP_4.4x9.7mm*",270]
      - ["^PUIAudio_SMT_0825_S_4_R*",270]
      - ["^USB_C_Receptacle_HRO_TYPE-C-31-M-12*",180]
      - ["^ESP32-W",270]
      - ["^SOIC127P798X216-8N",-90]
      - ["^SW_DIP_SPSTx01_Slide_Copal_CHS-01B_W7.62mm_P1.27mm",-180]
      - ["^BatteryHolder_Keystone_1060_1x2032",-180]
      - ["^SO-14",-90]
      - ["^HTSSOP-",270]
      - ["^USB_C_Receptacle_XKB_U262-16XN-4BVC11",0] #,1.44,0
      - ["^Relay_DPDT_Omron_G6K-2F-Y",270]
      - ["^RP2040-QFN-56",270]
      - ["^TO-277",90]
      - ["^SW_SPST_B3",90]
      - ["^Transformer_Ethernet_Pulse_HX0068ANL",270]
      - ["^JST_GH_SM",180]
      - ["^JST_PH_S",180]
      - ["^Diodes_PowerDI3333-8",270]
      - ["^Quectel_L80-R",270]
      - ["^SC-74-6",180]
      - ["^SOT-143",180]
      - ["^PinHeader_2x05_P1.27mm_Vertical",90] #,2.54,0.635
      - ["^LED_WS2812B-2020_PLCC4_2.0x2.0mm",90]
      - ["^^WSON-8-1EP_6x5mm_P1.27mm",-90]
      - ["^SOT95P280X145-5N", 180.0]
      - ["^MLP14_2P5X2P5_ONS", -90.0]
      - ["^TSOT-23-6", -90.0]
      - ["^SOTFL50P162X60-6N", -90.0]
      - ["^SSOP-8_2.95x2.8mm_P0.65mm", 180.0]
      - ["^CMM-4030DT-26154-TR", -90.0]
      - ["^PinSocket_1x05_P1.27mm_Vertical_SMD_Pin1Left", -90.0]
      - ["^PinHeader_2x20_P1.27mm_Vertical_SMD", -90.0]
      - ["TRRS-PJ-393", 90.0]
    offsets:
      - ["^USB_C_Receptacle_HCTL_HC-TYPE-C-16P-01A", "0,-1.3"]
      - ["^TRRS-PJ-393", "0,6.25"]
    # rotations_and_offsets:
    #   - field: Reference
    #     regex: U103
    #     angle: 180.0

import:
  - file: includes/set-text-variables.kibot.yaml
  - file: JLCPCB_stencil_with_THT
    definitions:
      _KIBOT_POS_ONLY_SMD: false
      _KIBOT_POS_PRE_TRANSFORM: fix_rotation

outputs:
  - name: JLCPCB
    type: compress
    options:
      format: ZIP
      output: '%f-%i%I%v.%x'
      # output: '%i%I%v.%x'
      files:
        - source: JLCPCB/*
          # from_cwd: true
          dest: ./
        - source: Manufacturing Notes/*
          from_cwd: true
          dest: ./
        - source: ../*.png
          dest: ./