# This script is called by the .github/workflows/render.yml workflow to generate images
# for documentation.
kibot:
  version: 1

global:
  # Sets the default output filename for all generated files. You likely don't have to change this.
  output: "%f-%i.%x"

preflight:  
  # These are off by default so it's possible to generate output files prior to the board being
  # completely finished (e.g. for draft review, etc.).
  run_erc: false
  run_drc: false
  # This is important to set to true so replacement of version and date strings in the release
  # build process works correctly.
  check_zone_fills: true
  # set_text_variables:
  #   # The revision will be the short git hash
  #   # We use ${git_hash} for the REV field in the worksheet (frame)
  #   - name: 'git_hash'
  #     command: 'git log -1 --format="%h" $KIBOT_PCB_NAME'
  #     before: 'Git:'
  #   # Coherent date and time for the schematic and PCB
  #   # This will be the time stamp of the files generation, not the commit times
  #   # We use `${date}` for the time field in the worksheet (frame)
  #   - name: 'date'
  #     command: 'date --iso-8601=minutes'

filters:
  - name: "exclude_any"
    type: "generic"
    comment: "Exclude logos, testpoints, fiducials and power"
    exclude_any:
      - column: Reference
        regex: "^(G|#|TP|F).*"

# This imports the KiBot scripts that actually do all the generation. If you want to
# generate different things/more things then change these to point to other .kibot.yaml files.
import:
  - file: includes/set-text-variables.kibot.yaml

outputs:
  - name: Blender Export
    comment: "3D file for Blender"
    type: blender_export
    dir: 3D
    options:
      render_options:
        transparent_background: true
        samples: 10
        resolution_x: 1920
        resolution_y: 1080
      pcb3d:
        download_lcsc: false
      outputs:
        - type: blender

  - name: 3D_top_view_HQ
    comment: "3D render from top (High Quality)"
    type: blender_export
    dir: 3D
    options:
      render_options:
        transparent_background: true
        samples: 10
        resolution_x: 1920
        resolution_y: 1080
      pcb3d:
        download_lcsc: false
      outputs:
        # - type: blender
        - type: render

  # - name: 3D_top_30_-20_view_HQ
  #   comment: "3D render from top 30 -20 (High Quality)"
  #   type: blender_export
  #   dir: 3D
  #   output_id: '_30_-20'
  #   options:
  #     render_options:
  #       transparent_background: true
  #       samples: 10
  #       resolution_x: 1920
  #       resolution_y: 1080
  #     point_of_view:
  #       rotate_x: 30
  #       rotate_z: -20
  #     pcb3d:
  #       download_lcsc: false
  #     outputs:
  #       # - type: blender
  #       - type: render

  # - name: 3D_bottom_view_HQ
  #   comment: "3D render from bottom (High Quality)"
  #   type: blender_export
  #   dir: 3D
  #   options:
  #     render_options:
  #       transparent_background: true
  #       samples: 10
  #       resolution_x: 1920
  #       resolution_y: 1080
  #     point_of_view:
  #       view : 'bottom'
  #       rotate_z: 180
  #     pcb3d:
  #       download_lcsc: false
  #     outputs:
  #       # - type: blender
  #       - type: render

  # - name: 3D_bottom_30_-20_view_HQ
  #   comment: "3D render from bottom 30 -20 (High Quality)"
  #   type: blender_export
  #   dir: 3D
  #   output_id: '_30_-20'
  #   options:
  #     render_options:
  #       transparent_background: true
  #       samples: 10
  #       resolution_x: 1920
  #       resolution_y: 1080
  #     point_of_view:
  #       view : 'bottom'
  #       rotate_x: 30
  #       rotate_z: 160
  #     pcb3d:
  #       download_lcsc: false
  #     outputs:
  #       # - type: blender
  #       - type: render

  # - name: 3D_front_view_HQ
  #   comment: "3D render from front (High Quality)"
  #   type: blender_export
  #   dir: 3D
  #   options:
  #     render_options:
  #       transparent_background: true
  #       samples: 10
  #       resolution_x: 1920
  #       resolution_y: 1080
  #     point_of_view:
  #       view : 'front'
  #     pcb3d:
  #       download_lcsc: false
  #     outputs:
  #       # - type: blender
  #       - type: render

  # - name: 3D_rear_view_HQ
  #   comment: "3D render from rear (High Quality)"
  #   type: blender_export
  #   dir: 3D
  #   options:
  #     render_options:
  #       transparent_background: true
  #       samples: 10
  #       resolution_x: 1920
  #       resolution_y: 1080
  #     point_of_view:
  #       view : 'rear'
  #     pcb3d:
  #       download_lcsc: false
  #     outputs:
  #       # - type: blender
  #       - type: render

  # - name: 3D_right_view_HQ
  #   comment: "3D render from right (High Quality)"
  #   type: blender_export
  #   dir: 3D
  #   options:
  #     render_options:
  #       transparent_background: true
  #       samples: 10
  #       resolution_x: 1920
  #       resolution_y: 1080
  #     point_of_view:
  #       view : 'right'
  #     pcb3d:
  #       download_lcsc: false
  #     outputs:
  #       # - type: blender
  #       - type: render

  # - name: 3D_left_view_HQ
  #   comment: "3D render from left (High Quality)"
  #   type: blender_export
  #   dir: 3D
  #   options:
  #     render_options:
  #       transparent_background: true
  #       samples: 10
  #       resolution_x: 1920
  #       resolution_y: 1080
  #     point_of_view:
  #       view : 'left'
  #     pcb3d:
  #       download_lcsc: false
  #     outputs:
  #       # - type: blender
  #       - type: render

